server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: cf-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/erojas14ths/cf-config-repo
          search-paths: ms-catalog-service
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
