apiVersion: v1
kind: Service
metadata:
  name: cf-config-service
  namespace: polar
  labels:
    app: cf-config-service
spec:
  type: ClusterIP
  selector:
    app: cf-config-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8888
